import {
  Activity,
  Baby,
  Beef,
  Diamond,
  Dumbbell,
  Film,
  Flame,
  Laptop,
  Users,
  Waves,
  type LucideIcon,
} from 'lucide-react'
import type { FacilityMeta, FacilityType } from '@/types'

// Professional, monochrome icon + subtle tinted background.
// No emoji — clean enterprise look.
export const facilityMeta: Record<FacilityType, FacilityMeta & { icon: LucideIcon; color: string }> = {
  billiard: {
    type: 'billiard',
    label: 'Bilyard zali',
    description: '2 ta stol, kiy/sharlar bilan',
    hoursFrom: 10,
    hoursTo: 23,
    capacity: 4,
    isFree: true,
    icon: Diamond,
    color: 'text-purple-600 bg-purple-50',
  },
  table_tennis: {
    type: 'table_tennis',
    label: 'Stol tennisi',
    description: '4 ta stol',
    hoursFrom: 9,
    hoursTo: 22,
    capacity: 4,
    isFree: true,
    icon: Activity,
    color: 'text-orange-600 bg-orange-50',
  },
  gym: {
    type: 'gym',
    label: 'Gym',
    description: 'Yopiq sport zal',
    hoursFrom: 6,
    hoursTo: 23,
    capacity: 12,
    isFree: true,
    icon: Dumbbell,
    color: 'text-red-600 bg-red-50',
  },
  bbq: {
    type: 'bbq',
    label: 'BBQ maydoni',
    description: 'Ochiq havoda manqal',
    hoursFrom: 11,
    hoursTo: 23,
    capacity: 10,
    isFree: false,
    pricePerHour: 50_000,
    icon: Beef,
    color: 'text-amber-600 bg-amber-50',
  },
  swimming_pool: {
    type: 'swimming_pool',
    label: 'Basseyn',
    description: '25m, ichki, isitiladigan',
    hoursFrom: 7,
    hoursTo: 22,
    capacity: 8,
    isFree: true,
    icon: Waves,
    color: 'text-blue-600 bg-blue-50',
  },
  sauna: {
    type: 'sauna',
    label: 'Sauna',
    description: 'Finlyandiya saunasi, 6 kishilik',
    hoursFrom: 15,
    hoursTo: 23,
    capacity: 6,
    isFree: false,
    pricePerHour: 80_000,
    icon: Flame,
    color: 'text-rose-600 bg-rose-50',
  },
  cinema: {
    type: 'cinema',
    label: 'Kinozal',
    description: '20 o\'rinli, 4K proyektor',
    hoursFrom: 12,
    hoursTo: 23,
    capacity: 20,
    isFree: false,
    pricePerHour: 150_000,
    icon: Film,
    color: 'text-indigo-600 bg-indigo-50',
  },
  kids_playground: {
    type: 'kids_playground',
    label: 'Bolalar maydoni',
    description: '3-10 yosh, nazoratchi bor',
    hoursFrom: 9,
    hoursTo: 20,
    capacity: 15,
    isFree: true,
    icon: Baby,
    color: 'text-pink-600 bg-pink-50',
  },
  conference: {
    type: 'conference',
    label: 'Yig\'ilish zali',
    description: '12 kishilik, proyektor + Wi-Fi',
    hoursFrom: 8,
    hoursTo: 22,
    capacity: 12,
    isFree: false,
    pricePerHour: 100_000,
    icon: Users,
    color: 'text-teal-600 bg-teal-50',
  },
  coworking: {
    type: 'coworking',
    label: 'Co-working',
    description: 'Ish joyi, kofe va Wi-Fi',
    hoursFrom: 8,
    hoursTo: 23,
    capacity: 20,
    isFree: true,
    icon: Laptop,
    color: 'text-emerald-600 bg-emerald-50',
  },
}

export const facilityList = Object.values(facilityMeta)
