import {
  Activity,
  Baby,
  Crown,
  Diamond,
  Dumbbell,
  Gamepad2,
  Library,
  Mic2,
  Monitor,
  Music,
  type LucideIcon,
} from 'lucide-react'
import type { FacilityMeta, FacilityType } from '@/types'

// Nurli Diyor Residence — -1 qavatda joylashgan 10 ta maxsus qulaylik.
// Har biri uchun professional Unsplash rasm (yuqori sifat, lazy loaded).
export const facilityMeta: Record<FacilityType, FacilityMeta & { icon: LucideIcon; color: string }> = {
  it_room: {
    type: 'it_room',
    label: 'IT xonasi',
    description: 'Zamonaviy kompyuterlar bilan jihozlangan zal',
    hoursFrom: 8,
    hoursTo: 22,
    capacity: 12,
    isFree: true,
    icon: Monitor,
    color: 'text-sky-600 bg-sky-50 dark:bg-sky-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&q=80&auto=format&fit=crop',
  },
  library: {
    type: 'library',
    label: 'Kutubxona',
    description: 'Mutolaa uchun shinam maskan, jim joy',
    hoursFrom: 9,
    hoursTo: 22,
    capacity: 20,
    isFree: true,
    icon: Library,
    color: 'text-amber-700 bg-amber-50 dark:bg-amber-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&q=80&auto=format&fit=crop',
  },
  gym: {
    type: 'gym',
    label: 'Sport zali',
    description: 'Professional trenajyorlar, yopiq zal',
    hoursFrom: 6,
    hoursTo: 23,
    capacity: 15,
    isFree: true,
    icon: Dumbbell,
    color: 'text-red-600 bg-red-50 dark:bg-red-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80&auto=format&fit=crop',
  },
  chess: {
    type: 'chess',
    label: 'Shaxmat xonasi',
    description: 'Intellektual hordiq, professional shaxmat to\'plamlari',
    hoursFrom: 10,
    hoursTo: 22,
    capacity: 8,
    isFree: true,
    icon: Crown,
    color: 'text-stone-700 bg-stone-100 dark:bg-stone-500/20',
    imageUrl: 'https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=1200&q=80&auto=format&fit=crop',
  },
  billiard: {
    type: 'billiard',
    label: 'Bilyard xonasi',
    description: 'Maroqli vaqt o\'tkazish uchun, 2 ta stol',
    hoursFrom: 10,
    hoursTo: 23,
    capacity: 8,
    isFree: true,
    icon: Diamond,
    color: 'text-purple-600 bg-purple-50 dark:bg-purple-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1615722440048-da4fd9202651?w=1200&q=80&auto=format&fit=crop',
  },
  table_tennis: {
    type: 'table_tennis',
    label: 'Tennis',
    description: 'Faol dam olish zonasi, 4 ta stol',
    hoursFrom: 9,
    hoursTo: 22,
    capacity: 8,
    isFree: true,
    icon: Activity,
    color: 'text-orange-600 bg-orange-50 dark:bg-orange-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1611251135345-18c56206b863?w=1200&q=80&auto=format&fit=crop',
  },
  karaoke: {
    type: 'karaoke',
    label: 'Karaoke',
    description: 'Ko\'ngilochar markaz, professional tovush tizimi',
    hoursFrom: 14,
    hoursTo: 23,
    capacity: 12,
    isFree: false,
    pricePerHour: 80_000,
    icon: Mic2,
    color: 'text-pink-600 bg-pink-50 dark:bg-pink-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=1200&q=80&auto=format&fit=crop',
  },
  playstation: {
    type: 'playstation',
    label: 'PlayStation xonasi',
    description: 'O\'yin ixlosmandlari uchun, PS5 + 4K TV',
    hoursFrom: 10,
    hoursTo: 23,
    capacity: 6,
    isFree: false,
    pricePerHour: 50_000,
    icon: Gamepad2,
    color: 'text-indigo-600 bg-indigo-50 dark:bg-indigo-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=1200&q=80&auto=format&fit=crop',
  },
  piano: {
    type: 'piano',
    label: 'Pianino xonasi',
    description: 'Musiqiy ijod maskani, akustik pianino',
    hoursFrom: 10,
    hoursTo: 22,
    capacity: 4,
    isFree: true,
    icon: Music,
    color: 'text-teal-600 bg-teal-50 dark:bg-teal-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&q=80&auto=format&fit=crop',
  },
  kids_playground: {
    type: 'kids_playground',
    label: 'Bolalar maydonchasi',
    description: 'Qishki va yozgi zonalar, nazoratchi bor',
    hoursFrom: 9,
    hoursTo: 20,
    capacity: 20,
    isFree: true,
    icon: Baby,
    color: 'text-rose-600 bg-rose-50 dark:bg-rose-500/15',
    imageUrl: 'https://images.unsplash.com/photo-1597531072931-1b9eb91d4e92?w=1200&q=80&auto=format&fit=crop',
  },
}

export const facilityList = Object.values(facilityMeta)
