# Generated by Django 5.1.15 on 2026-06-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('it_room', 'IT xonasi'), ('library', 'Kutubxona'), ('gym', 'Sport zali'), ('chess', 'Shaxmat xonasi'), ('billiard', 'Bilyard xonasi'), ('table_tennis', 'Tennis'), ('karaoke', 'Karaoke'), ('playstation', 'PlayStation xonasi'), ('piano', 'Pianino xonasi'), ('kids_playground', 'Bolalar maydonchasi')], max_length=24, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name', max_length=40)),
                ('image_url', models.URLField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Tailwind tint classes', max_length=80)),
                ('hours_from', models.PositiveSmallIntegerField(default=8)),
                ('hours_to', models.PositiveSmallIntegerField(default=22)),
                ('capacity', models.PositiveSmallIntegerField(default=8)),
                ('is_free', models.BooleanField(default=True)),
                ('price_per_hour', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LotteryWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_name', models.CharField(max_length=120)),
                ('winner_name', models.CharField(help_text='Use masked name, e.g. "Akbar A."', max_length=120)),
                ('ticket_number', models.CharField(max_length=20)),
                ('prize', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('drawn_at', models.DateField()),
                ('verification_hash', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-drawn_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('info', 'Info'), ('event', 'Event'), ('celebration', 'Celebration'), ('warning', 'Warning')], default='info', max_length=16)),
                ('kicker', models.CharField(blank=True, max_length=40)),
                ('published_at', models.DateTimeField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('block_count', models.PositiveIntegerField(default=5)),
                ('floor_count', models.PositiveIntegerField(default=9)),
                ('apartment_count', models.PositiveIntegerField(default=0)),
                ('construction_progress', models.PositiveSmallIntegerField(default=0)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('estimated_delivery_label', models.CharField(blank=True, max_length=80)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('icon_name', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('total_floors', models.PositiveSmallIntegerField(default=9)),
                ('completed_floors', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='public.project')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='renders/')),
                ('image_url', models.URLField(blank=True, help_text='External URL fallback if no upload')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='public.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
