# Generated by Django 5.1.15 on 2026-06-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('month', models.DateField(help_text='Oy boshi sanasi (1-kuni), masalan: 2026-06-01')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Rasm')], default='video', max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='monthly_media/')),
                ('url', models.URLField(blank=True, help_text='Tashqi video/rasm URL (YouTube, CDN va h.k.)')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oylik media',
                'verbose_name_plural': 'Oylik medialar',
                'ordering': ['-month', 'order'],
            },
        ),
    ]
