# Generated by Django 5.1.15 on 2026-06-29 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_add_monthly_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['order', 'label'], 'verbose_name': 'Qulaylik', 'verbose_name_plural': 'Qulayliklar'},
        ),
        migrations.AlterModelOptions(
            name='constructionblock',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Qurilish bloki', 'verbose_name_plural': 'Qurilish bloklari'},
        ),
        migrations.AlterModelOptions(
            name='lotterywinner',
            options={'ordering': ['-drawn_at'], 'verbose_name': 'Omadli mijoz', 'verbose_name_plural': 'Omadli mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-is_pinned', '-published_at'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'Loyiha', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='projectrender',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Render rasm', 'verbose_name_plural': 'Render rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='projectstat',
            options={'ordering': ['order', 'key'], 'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistikalar'},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=8, verbose_name="Sig'im (kishi)"),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='Rang (Tailwind klasslari)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.CharField(blank=True, max_length=240, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='hours_from',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Ochilish vaqti (soat)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='hours_to',
            field=models.PositiveSmallIntegerField(default=22, verbose_name='Yopilish vaqti (soat)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Lucide ikonka nomi'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Bepul'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='kind',
            field=models.CharField(choices=[('it_room', 'IT xonasi'), ('library', 'Kutubxona'), ('gym', 'Sport zali'), ('chess', 'Shaxmat xonasi'), ('billiard', 'Bilyard xonasi'), ('table_tennis', 'Tennis'), ('karaoke', 'Karaoke'), ('playstation', 'PlayStation xonasi'), ('piano', 'Pianino xonasi'), ('kids_playground', 'Bolalar maydonchasi')], max_length=24, unique=True, verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='label',
            field=models.CharField(max_length=80, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=0, verbose_name="Narx (soatiga, so'm)"),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='completed_floors',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tugallangan qavatlar'),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Topshirish sanasi'),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Blok nomi'),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Foiz (0–100)'),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='public.project', verbose_name='Loyiha'),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='status',
            field=models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('active', 'Qurilmoqda'), ('completed', 'Tugatilgan')], default='active', max_length=12, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='constructionblock',
            name='total_floors',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='Jami qavatlar'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='drawn_at',
            field=models.DateField(verbose_name="O'tkazilgan sana"),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='lottery_name',
            field=models.CharField(max_length=120, verbose_name='Tanlов nomi'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='prize',
            field=models.CharField(max_length=160, verbose_name='Sovrin'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='ticket_number',
            field=models.CharField(max_length=20, verbose_name='Chipta raqami'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tasdiqlash kodi (hash)'),
        ),
        migrations.AlterField(
            model_name='lotterywinner',
            name='winner_name',
            field=models.CharField(help_text='Yopiq nom ishlatng, masalan: "Akbar A."', max_length=120, verbose_name="G'olib ismi"),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='monthly_media/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Rasm')], default='video', max_length=8, verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='month',
            field=models.DateField(help_text='Oy boshi sanasi (1-kuni), masalan: 2026-06-01', verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='Muqova rasmi (URL)'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='monthlymedia',
            name='url',
            field=models.URLField(blank=True, help_text="YouTube yoki CDN havolasi (fayl bo'lmasa)", verbose_name='Tashqi URL'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=models.TextField(blank=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Yuqorida qoldirilsin'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='kicker',
            field=models.CharField(blank=True, max_length=40, verbose_name='Kicker (qisqa tag)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='published_at',
            field=models.DateTimeField(verbose_name="E'lon qilingan vaqt"),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='tone',
            field=models.CharField(choices=[('info', "Ma'lumot"), ('event', 'Tadbir'), ('celebration', 'Bayram'), ('warning', 'Ogohlantirish')], default='info', max_length=16, verbose_name='Ohang'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=240, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='project',
            name='apartment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Xonadonlar soni'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_count',
            field=models.PositiveIntegerField(default=5, verbose_name='Bloklar soni'),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Qurilish foizi (0–100)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Taxminiy topshirish sanasi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_delivery_label',
            field=models.CharField(blank=True, max_length=80, verbose_name="Topshirish yorlig'i"),
        ),
        migrations.AlterField(
            model_name='project',
            name='floor_count',
            field=models.PositiveIntegerField(default=9, verbose_name='Qavatlar soni'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Tanlangan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Joylashuv belgisi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, max_length=240, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='projectrender',
            name='caption',
            field=models.CharField(blank=True, max_length=160, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='projectrender',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='renders/', verbose_name='Rasm fayli'),
        ),
        migrations.AlterField(
            model_name='projectrender',
            name='image_url',
            field=models.URLField(blank=True, help_text="Fayl yuklanmagan bo'lsa ishlatiladi", verbose_name='Tashqi URL'),
        ),
        migrations.AlterField(
            model_name='projectrender',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='projectrender',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='public.project', verbose_name='Loyiha'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='icon_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ikonka nomi'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='key',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Kalit'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='label',
            field=models.CharField(max_length=80, verbose_name='Yorliq'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, verbose_name='Prefiks'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, verbose_name='Suffiks'),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Qiymat'),
        ),
        migrations.CreateModel(
            name='BlockFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Qavat raqami')),
                ('status', models.CharField(choices=[('done', 'Tugatilgan'), ('in_progress', 'Qurilmoqda'), ('not_started', 'Boshlanmagan')], default='not_started', max_length=16, verbose_name='Holat')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Tugatilgan sana')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='public.constructionblock', verbose_name='Blok')),
            ],
            options={
                'verbose_name': 'Qavat',
                'verbose_name_plural': 'Qavatlar',
                'ordering': ['number'],
                'unique_together': {('block', 'number')},
            },
        ),
    ]
